### ISSUE TITLE
Error: npm run generateTypeScriptTypes

### ISSUE THREAD

**Issue by gaitat** [MeasureAuthoringTool/model-info-parser#258]
On a windows machine with node 14.17.0, after `npm install` I run `npm run generateTypeScriptTypes` and I get the following error message:

PS C:\Users\Downloads\model-info-parser> npm run generateTypeScriptTypes

> model-info-parser@1.0.7 generateTypeScriptTypes C:\Users\Downloads\model-info-parser
> ts-node src/generateTypeScriptTypes.ts

C:\Users\Downloads\model-info-parser\src\model\dataTypes\DataType.ts:39
      throw new Error(
            ^
Error: Cannot create DataType for relative path "C:\Users\Downloads\model-info-parser\src\model\dataTypes\system/system"
    at Function.getInstance (C:\Users\Downloads\model-info-parser\src\model\dataTypes\DataType.ts:39:13)
    at Object.<anonymous> (C:\Users\Downloads\model-info-parser\src\model\dataTypes\system\SystemString.ts:3:25)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (C:\Users\Downloads\model-info-parser\node_modules\ts-node\src\index.ts:1225:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Downloads\model-info-parser\node_modules\ts-node\src\index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! model-info-parser@1.0.7 generateTypeScriptTypes: `ts-node src/generateTypeScriptTypes.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the model-info-parser@1.0.7 generateTypeScriptTypes script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2022-01-22T21_02_21_786Z-debug.log

**Comment by gaitat** [comment]
After further debugging this is not a node version issue but rather a machine type version.
On Linux machines the application runs as expected.
